site_name: Biology Problems OER
theme:
  name: material
nav:
  - Home: index.md
  - Biochemistry:
      - Overview: biochemistry/index.md
      - Chapter 1: biochemistry/chapter1.md
      - Chapter 2: biochemistry/chapter2.md
  - Genetics:
      - Overview: genetics/index.md
      - Chapter 1: genetics/chapter1.md
      - Chapter 2: genetics/chapter2.md
