site_name: Biology Problems OER
theme:
  name: material
nav:
  - Home: index.md
  - Biochemistry:
      - Chapter 1: biochemistry/chapter1/index.md
      - Chapter 2: biochemistry/chapter2/index.md
  - Genetics:
      - Chapter 1: genetics/chapter1/index.md
      - Chapter 2: genetics/chapter2/index.md
