site_name: Biology Problems OER
theme:
  name: material
nav:
  - Home: index.md
  - Biochemistry:
      - List of Biochemistry Topics: biochemistry/index.md
      - Topic 1: biochemistry/topic1/index.md
      - Topic 2: biochemistry/topic2/index.md
  - Genetics:
      - List of Genetics Topics: genetics/index.md
      - Topic 1: genetics/topic1/index.md
      - Topic 2: genetics/topic2/index.md
